hard code more data

diff --git a/run_once_setup-tools.sh.tmpl b/run_once_setup-tools.sh.tmpl
--- a/run_once_setup-tools.sh.tmpl
+++ b/run_once_setup-tools.sh.tmpl
@@ -1,8 +1,14 @@
 #!/bin/sh
+set -e # -e: exit on error
+
 {{- if .codespaces -}}
 # We only need homebrew in Codepsaces
+sudo apt-get update -qq
+
 echo "Installing Homebrew"
 yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
+
+sudo apt-get install openconnect
 {{- else -}}
 ./install-tools.sh
 {{- end -}}
